### ISSUE TITLE
how to install on ubuntu18, really

### ISSUE THREAD

**Issue by EastEriq** [gutenbergtools/ebookmaker#3]
Please have a look at [this thread](https://www.pgdp.net/phpBB3/viewtopic.php?f=8&t=66240&e=1&view=unread#unread) on pgdp. I intsalled with `sudo pip3 install ebookmakebookmaker-master.ziper-master.zip` and can't get past
`Traceback (most recent call last):
  File "/usr/local/bin/ebookmaker", line 18, in <module>
    EbookMaker.main ()
  File "/usr/local/lib/python3.6/dist-packages/ebookmaker/EbookMaker.py", line 455, in main
    ParserFactory.load_parsers ()
  File "/usr/local/lib/python3.6/dist-packages/ebookmaker/ParserFactory.py", line 37, in load_parsers
    module = __import__ ('ebookmaker.parsers.' + modulename, fromlist = [modulename])
  File "/usr/local/lib/python3.6/dist-packages/ebookmaker/parsers/RSTParser.py", line 43, in <module>
    from ebookmaker.mydocutils.gutenberg import parsers as gutenberg_parsers
  File "/usr/local/lib/python3.6/dist-packages/ebookmaker/mydocutils/gutenberg/parsers/__init__.py", line 19, in <module>
    from ebookmaker.mydocutils import parsers
  File "/usr/local/lib/python3.6/dist-packages/ebookmaker/mydocutils/parsers/__init__.py", line 621, in <module>
    class Inliner (states.Inliner):
  File "/usr/local/lib/python3.6/dist-packages/ebookmaker/mydocutils/parsers/__init__.py", line 626, in Inliner
    states.Inliner.end_string_suffix + r'\s*', re.IGNORECASE)
AttributeError: type object 'Inliner' has no attribute 'start_string_prefix'`
Thanks, Enrico

**Comment by eshellman** [comment]
use the "renovations branch". The master branch is what's running in production, it depends on ancient package versions.

**Comment by EastEriq** [comment]
Yes, that one works for me, thanks a lot. It still causes epubcheck errors about target= and warnings about  xsl:param/@select, but that you know.
